# 成人内容翻译词典
# 用于处理翻译API无法处理的敏感内容

# 生理相关
physiological_terms:
  description: "生理相关词汇翻译"
  entries:
    - english: "cum"
      chinese: "精液"
      context: "生理描述"
      priority: "high"
      note: "翻译API可能过滤此内容"
    
    - english: "semen"
      chinese: "精液"
      context: "生理描述"
      priority: "high"
    
    - english: "sperm"
      chinese: "精子"
      context: "生理描述"
      priority: "high"
    
    - english: "penis"
      chinese: "阴茎"
      context: "生理描述"
      priority: "high"
    
    - english: "vagina"
      chinese: "阴道"
      context: "生理描述"
      priority: "high"
    
    - english: "breast"
      chinese: "乳房"
      context: "生理描述"
      priority: "high"
    
    - english: "nipple"
      chinese: "乳头"
      context: "生理描述"
      priority: "high"
    
    - english: "clitoris"
      chinese: "阴蒂"
      context: "生理描述"
      priority: "high"
    
    - english: "anus"
      chinese: "肛门"
      context: "生理描述"
      priority: "high"
    
    - english: "prostate"
      chinese: "前列腺"
      context: "生理描述"
      priority: "high"

# 性行为相关
sexual_behavior:
  description: "性行为相关词汇翻译"
  entries:
    - english: "sex"
      chinese: "性行为"
      context: "行为描述"
      priority: "high"
    
    - english: "sexual"
      chinese: "性的"
      context: "形容词"
      priority: "high"
    
    - english: "intercourse"
      chinese: "性交"
      context: "行为描述"
      priority: "high"
    
    - english: "masturbation"
      chinese: "手淫"
      context: "行为描述"
      priority: "high"
    
    - english: "orgasm"
      chinese: "性高潮"
      context: "生理反应"
      priority: "high"
    
    - english: "ejaculation"
      chinese: "射精"
      context: "生理反应"
      priority: "high"
    
    - english: "erection"
      chinese: "勃起"
      context: "生理状态"
      priority: "high"
    
    - english: "arousal"
      chinese: "性兴奋"
      context: "生理状态"
      priority: "high"
    
    - english: "lust"
      chinese: "性欲"
      context: "心理状态"
      priority: "high"
    
    - english: "desire"
      chinese: "欲望"
      context: "心理状态"
      priority: "high"

# 性取向相关
sexual_orientation:
  description: "性取向相关词汇翻译"
  entries:
    - english: "homosexual"
      chinese: "同性恋"
      context: "性取向"
      priority: "high"
    
    - english: "heterosexual"
      chinese: "异性恋"
      context: "性取向"
      priority: "high"
    
    - english: "bisexual"
      chinese: "双性恋"
      context: "性取向"
      priority: "high"
    
    - english: "asexual"
      chinese: "无性恋"
      context: "性取向"
      priority: "high"

# 性行为方式
sexual_acts:
  description: "性行为方式词汇翻译"
  entries:
    - english: "oral"
      chinese: "口交"
      context: "性行为方式"
      priority: "high"
    
    - english: "anal"
      chinese: "肛交"
      context: "性行为方式"
      priority: "high"
    
    - english: "vaginal"
      chinese: "阴道性交"
      context: "性行为方式"
      priority: "high"
    
    - english: "foreplay"
      chinese: "前戏"
      context: "性行为阶段"
      priority: "high"
    
    - english: "penetration"
      chinese: "插入"
      context: "性行为动作"
      priority: "high"
    
    - english: "thrust"
      chinese: "抽插"
      context: "性行为动作"
      priority: "high"

# 暴力性行为相关
violent_sexual_behavior:
  description: "暴力性行为相关词汇翻译"
  entries:
    - english: "rape"
      chinese: "强奸"
      context: "暴力性行为"
      priority: "high"
      note: "翻译API可能过滤此内容"
    
    - english: "raping"
      chinese: "强奸"
      context: "暴力性行为"
      priority: "high"
    
    - english: "raped"
      chinese: "被强奸"
      context: "暴力性行为"
      priority: "high"
    
    - english: "bestiality"
      chinese: "兽交"
      context: "性行为方式"
      priority: "high"
      note: "翻译API可能过滤此内容"
    
    - english: "beastiality"
      chinese: "兽交"
      context: "性行为方式"
      priority: "high"

# 超自然性内容
supernatural_sexual:
  description: "超自然性内容词汇翻译"
  entries:
    - english: "succubus"
      chinese: "魅魔"
      context: "超自然生物"
      priority: "high"
    
    - english: "succubi"
      chinese: "魅魔"
      context: "超自然生物"
      priority: "high"
    
    - english: "incubus"
      chinese: "梦魔"
      context: "超自然生物"
      priority: "high"
    
    - english: "incubi"
      chinese: "梦魔"
      context: "超自然生物"
      priority: "high"

# 性相关疾病
sexual_diseases:
  description: "性相关疾病词汇翻译"
  entries:
    - english: "STD"
      chinese: "性传播疾病"
      context: "医学术语"
      priority: "high"
    
    - english: "STI"
      chinese: "性传播感染"
      context: "医学术语"
      priority: "high"
    
    - english: "HIV"
      chinese: "艾滋病病毒"
      context: "医学术语"
      priority: "high"
    
    - english: "AIDS"
      chinese: "艾滋病"
      context: "医学术语"
      priority: "high"

# 性相关物品
sexual_items:
  description: "性相关物品词汇翻译"
  entries:
    - english: "condom"
      chinese: "避孕套"
      context: "避孕用品"
      priority: "high"
    
    - english: "contraceptive"
      chinese: "避孕药"
      context: "避孕用品"
      priority: "high"
    
    - english: "lubricant"
      chinese: "润滑剂"
      context: "性用品"
      priority: "high"
    
    - english: "vibrator"
      chinese: "振动器"
      context: "性用品"
      priority: "high"
    
    - english: "dildo"
      chinese: "假阳具"
      context: "性用品"
      priority: "high"

# 性相关状态
sexual_states:
  description: "性相关状态词汇翻译"
  entries:
    - english: "virgin"
      chinese: "处女/处男"
      context: "性经验状态"
      priority: "high"
    
    - english: "virginity"
      chinese: "童贞"
      context: "性经验状态"
      priority: "high"
    
    - english: "promiscuous"
      chinese: "滥交的"
      context: "性行为描述"
      priority: "high"
    
    - english: "fidelity"
      chinese: "忠诚"
      context: "性关系状态"
      priority: "high"
    
    - english: "infidelity"
      chinese: "不忠"
      context: "性关系状态"
      priority: "high"

# 性相关情感
sexual_emotions:
  description: "性相关情感词汇翻译"
  entries:
    - english: "passion"
      chinese: "激情"
      context: "情感描述"
      priority: "high"
    
    - english: "intimacy"
      chinese: "亲密"
      context: "情感描述"
      priority: "high"
    
    - english: "romance"
      chinese: "浪漫"
      context: "情感描述"
      priority: "high"
    
    - english: "seduction"
      chinese: "诱惑"
      context: "行为描述"
      priority: "high"
    
    - english: "flirt"
      chinese: "调情"
      context: "行为描述"
      priority: "high"
    
    - english: "seduce"
      chinese: "诱惑"
      context: "性行为动作"
      priority: "high"
    
    - english: "seducing"
      chinese: "诱惑"
      context: "性行为动作"
      priority: "high"

# 性相关动作
sexual_actions:
  description: "性相关动作词汇翻译"
  entries:
    - english: "kiss"
      chinese: "接吻"
      context: "亲密动作"
      priority: "high"
    
    - english: "hug"
      chinese: "拥抱"
      context: "亲密动作"
      priority: "high"
    
    - english: "caress"
      chinese: "爱抚"
      context: "亲密动作"
      priority: "high"
    
    - english: "fondle"
      chinese: "抚摸"
      context: "亲密动作"
      priority: "high"
    
    - english: "touch"
      chinese: "触摸"
      context: "亲密动作"
      priority: "high"

# 性相关描述词
sexual_descriptors:
  description: "性相关描述词翻译"
  entries:
    - english: "naked"
      chinese: "裸体"
      context: "身体状态"
      priority: "high"
    
    - english: "nude"
      chinese: "裸体"
      context: "身体状态"
      priority: "high"
    
    - english: "bare"
      chinese: "裸露"
      context: "身体状态"
      priority: "high"
    
    - english: "exposed"
      chinese: "暴露"
      context: "身体状态"
      priority: "high"
    
    - english: "clothed"
      chinese: "穿着衣服"
      context: "身体状态"
      priority: "high"
    
    - english: "dressed"
      chinese: "穿着"
      context: "身体状态"
      priority: "high"
    
    - english: "dirty dreams"
      chinese: "淫梦"
      context: "性相关描述"
      priority: "high"
    
    - english: "sexual prowess"
      chinese: "性能力"
      context: "性相关描述"
      priority: "high"

# 性相关时间描述
sexual_time_descriptions:
  description: "性相关时间描述词汇翻译"
  entries:
    - english: "forever"
      chinese: "永远"
      context: "时间描述"
      priority: "high"
    
    - english: "eternity"
      chinese: "永恒"
      context: "时间描述"
      priority: "high"
    
    - english: "moment"
      chinese: "瞬间"
      context: "时间描述"
      priority: "high"
    
    - english: "instant"
      chinese: "瞬间"
      context: "时间描述"
      priority: "high"

# 游戏特有成人概念
game_specific_adult:
  description: "游戏特有成人概念翻译"
  entries:
    - english: "fertilin"
      chinese: "生育素"
      context: "游戏概念"
      priority: "high"
      note: "游戏特有概念"
    
    - english: "low fertilin"
      chinese: "生育素不足"
      context: "游戏状态"
      priority: "high"
    
    - english: "zero fertilin"
      chinese: "生育素为零"
      context: "游戏状态"
      priority: "high"
