# 翻译字典配置文件
# 存储常用词汇的翻译对照关系

# 基础词汇翻译
basic_terms:
  description: "基础词汇翻译对照"
  entries:
    # 游戏基础概念
    - english: "Health"
      chinese: "生命值"
      context: "游戏属性"
      priority: "high"
    
    - english: "Mood"
      chinese: "心情"
      context: "游戏属性"
      priority: "high"
    
    - english: "Food"
      chinese: "食物"
      context: "游戏物品"
      priority: "high"
    
    - english: "Weapon"
      chinese: "武器"
      context: "游戏物品"
      priority: "high"
    
    - english: "Armor"
      chinese: "护甲"
      context: "游戏物品"
      priority: "high"
    
    - english: "Medicine"
      chinese: "药物"
      context: "游戏物品"
      priority: "high"
    
    - english: "Research"
      chinese: "研究"
      context: "游戏机制"
      priority: "high"
    
    - english: "Construction"
      chinese: "建造"
      context: "游戏机制"
      priority: "high"
    
    - english: "Cooking"
      chinese: "烹饪"
      context: "游戏机制"
      priority: "high"
    
    - english: "Mining"
      chinese: "采矿"
      context: "游戏机制"
      priority: "high"

# RimWorld 特有术语
rimworld_terms:
  description: "RimWorld 特有术语翻译"
  entries:
    - english: "Colonist"
      chinese: "殖民者"
      context: "游戏角色"
      priority: "high"
    
    - english: "Pawn"
      chinese: "角色"
      context: "游戏角色"
      priority: "high"
    
    - english: "Raid"
      chinese: "袭击"
      context: "游戏事件"
      priority: "high"
    
    - english: "Mood Debuff"
      chinese: "心情减益"
      context: "游戏机制"
      priority: "medium"
    
    - english: "Mood Buff"
      chinese: "心情增益"
      context: "游戏机制"
      priority: "medium"
    
    - english: "Mental Break"
      chinese: "精神崩溃"
      context: "游戏机制"
      priority: "high"
    
    - english: "Break Risk"
      chinese: "崩溃风险"
      context: "游戏机制"
      priority: "medium"
    
    - english: "Work Priority"
      chinese: "工作优先级"
      context: "游戏机制"
      priority: "medium"
    
    - english: "Restrict"
      chinese: "限制"
      context: "游戏机制"
      priority: "medium"
    
    - english: "Assign"
      chinese: "分配"
      context: "游戏机制"
      priority: "medium"

# 技术术语
technical_terms:
  description: "技术术语翻译"
  entries:
    - english: "Def"
      chinese: "定义"
      context: "技术术语"
      priority: "low"
    
    - english: "XML"
      chinese: "XML"
      context: "技术术语"
      priority: "low"
    
    - english: "Mod"
      chinese: "模组"
      context: "技术术语"
      priority: "medium"
    
    - english: "Patch"
      chinese: "补丁"
      context: "技术术语"
      priority: "low"
    
    - english: "Override"
      chinese: "覆盖"
      context: "技术术语"
      priority: "low"
    
    - english: "Inherit"
      chinese: "继承"
      context: "技术术语"
      priority: "low"
    
    - english: "Abstract"
      chinese: "抽象"
      context: "技术术语"
      priority: "low"
    
    - english: "Parent"
      chinese: "父级"
      context: "技术术语"
      priority: "low"
    
    - english: "Child"
      chinese: "子级"
      context: "技术术语"
      priority: "low"

# 物品类型
item_types:
  description: "物品类型翻译"
  entries:
    - english: "ThingDef"
      chinese: "物品定义"
      context: "物品类型"
      priority: "medium"
    
    - english: "PawnKindDef"
      chinese: "角色类型定义"
      context: "物品类型"
      priority: "medium"
    
    - english: "FactionDef"
      chinese: "派系定义"
      context: "物品类型"
      priority: "medium"
    
    - english: "ResearchProjectDef"
      chinese: "研究项目定义"
      context: "物品类型"
      priority: "medium"
    
    - english: "RecipeDef"
      chinese: "配方定义"
      context: "物品类型"
      priority: "medium"
    
    - english: "WorkTypeDef"
      chinese: "工作类型定义"
      context: "物品类型"
      priority: "medium"
    
    - english: "SkillDef"
      chinese: "技能定义"
      context: "物品类型"
      priority: "medium"
    
    - english: "TraitDef"
      chinese: "特质定义"
      context: "物品类型"
      priority: "medium"

# 翻译规则
translation_rules:
  description: "翻译规则和约定"
  rules:
    - rule: "专有名词保持英文"
      example: "XML, API, GUI"
      priority: "high"
    
    - rule: "游戏内物品名称保持原意"
      example: "Steel -> 钢铁, Wood -> 木材"
      priority: "high"
    
    - rule: "技能名称使用动词形式"
      example: "Mining -> 采矿, Cooking -> 烹饪"
      priority: "medium"
    
    - rule: "状态描述使用形容词"
      example: "Happy -> 快乐, Sad -> 悲伤"
      priority: "medium"
    
    - rule: "动作描述使用动词"
      example: "Attack -> 攻击, Defend -> 防御"
      priority: "medium"

# 常用短语
common_phrases:
  description: "常用短语翻译"
  entries:
    - english: "Ate without table"
      chinese: "在无桌环境下用餐"
      context: "心情描述"
      priority: "high"
    
    - english: "Slept on ground"
      chinese: "睡在地上"
      context: "心情描述"
      priority: "high"
    
    - english: "Ate raw food"
      chinese: "食用生食"
      context: "心情描述"
      priority: "high"
    
    - english: "Wearing tattered apparel"
      chinese: "穿着破烂服装"
      context: "心情描述"
      priority: "high"
    
    - english: "Slept in the cold"
      chinese: "在寒冷中睡觉"
      context: "心情描述"
      priority: "high"
    
    - english: "Slept in the heat"
      chinese: "在炎热中睡觉"
      context: "心情描述"
      priority: "high"
    
    - english: "Slept in the dark"
      chinese: "在黑暗中睡觉"
      context: "心情描述"
      priority: "high"
    
    - english: "Slept outside"
      chinese: "在户外睡觉"
      context: "心情描述"
      priority: "high"

# 成人内容翻译词典（需要手动翻译的内容）
adult_content:
  description: "成人内容翻译词典 - 用于处理翻译API无法处理的敏感内容"
  entries:
    # 生理相关
    - english: "cum"
      chinese: "精液"
      context: "生理描述"
      priority: "high"
      note: "翻译API可能过滤此内容"
    
    - english: "semen"
      chinese: "精液"
      context: "生理描述"
      priority: "high"
    
    - english: "sperm"
      chinese: "精子"
      context: "生理描述"
      priority: "high"
    
    - english: "penis"
      chinese: "阴茎"
      context: "生理描述"
      priority: "high"
    
    - english: "vagina"
      chinese: "阴道"
      context: "生理描述"
      priority: "high"
    
    - english: "breast"
      chinese: "乳房"
      context: "生理描述"
      priority: "high"
    
    - english: "nipple"
      chinese: "乳头"
      context: "生理描述"
      priority: "high"
    
    - english: "clitoris"
      chinese: "阴蒂"
      context: "生理描述"
      priority: "high"
    
    - english: "anus"
      chinese: "肛门"
      context: "生理描述"
      priority: "high"
    
    - english: "prostate"
      chinese: "前列腺"
      context: "生理描述"
      priority: "high"
    
    # 性行为相关
    - english: "sex"
      chinese: "性行为"
      context: "行为描述"
      priority: "high"
    
    - english: "sexual"
      chinese: "性的"
      context: "形容词"
      priority: "high"
    
    - english: "intercourse"
      chinese: "性交"
      context: "行为描述"
      priority: "high"
    
    - english: "masturbation"
      chinese: "手淫"
      context: "行为描述"
      priority: "high"
    
    - english: "orgasm"
      chinese: "性高潮"
      context: "生理反应"
      priority: "high"
    
    - english: "ejaculation"
      chinese: "射精"
      context: "生理反应"
      priority: "high"
    
    - english: "erection"
      chinese: "勃起"
      context: "生理状态"
      priority: "high"
    
    - english: "arousal"
      chinese: "性兴奋"
      context: "生理状态"
      priority: "high"
    
    - english: "lust"
      chinese: "性欲"
      context: "心理状态"
      priority: "high"
    
    - english: "desire"
      chinese: "欲望"
      context: "心理状态"
      priority: "high"
    
    # 性取向相关
    - english: "homosexual"
      chinese: "同性恋"
      context: "性取向"
      priority: "high"
    
    - english: "heterosexual"
      chinese: "异性恋"
      context: "性取向"
      priority: "high"
    
    - english: "bisexual"
      chinese: "双性恋"
      context: "性取向"
      priority: "high"
    
    - english: "asexual"
      chinese: "无性恋"
      context: "性取向"
      priority: "high"
    
    # 性行为方式
    - english: "oral"
      chinese: "口交"
      context: "性行为方式"
      priority: "high"
    
    - english: "anal"
      chinese: "肛交"
      context: "性行为方式"
      priority: "high"
    
    - english: "vaginal"
      chinese: "阴道性交"
      context: "性行为方式"
      priority: "high"
    
    - english: "foreplay"
      chinese: "前戏"
      context: "性行为阶段"
      priority: "high"
    
    - english: "penetration"
      chinese: "插入"
      context: "性行为动作"
      priority: "high"
    
    - english: "thrust"
      chinese: "抽插"
      context: "性行为动作"
      priority: "high"
    
    # 性相关疾病
    - english: "STD"
      chinese: "性传播疾病"
      context: "医学术语"
      priority: "high"
    
    - english: "STI"
      chinese: "性传播感染"
      context: "医学术语"
      priority: "high"
    
    - english: "HIV"
      chinese: "艾滋病病毒"
      context: "医学术语"
      priority: "high"
    
    - english: "AIDS"
      chinese: "艾滋病"
      context: "医学术语"
      priority: "high"
    
    # 性相关物品
    - english: "condom"
      chinese: "避孕套"
      context: "避孕用品"
      priority: "high"
    
    - english: "contraceptive"
      chinese: "避孕药"
      context: "避孕用品"
      priority: "high"
    
    - english: "lubricant"
      chinese: "润滑剂"
      context: "性用品"
      priority: "high"
    
    - english: "vibrator"
      chinese: "振动器"
      context: "性用品"
      priority: "high"
    
    - english: "dildo"
      chinese: "假阳具"
      context: "性用品"
      priority: "high"
    
    # 性相关状态
    - english: "virgin"
      chinese: "处女/处男"
      context: "性经验状态"
      priority: "high"
    
    - english: "virginity"
      chinese: "童贞"
      context: "性经验状态"
      priority: "high"
    
    - english: "promiscuous"
      chinese: "滥交的"
      context: "性行为描述"
      priority: "high"
    
    - english: "fidelity"
      chinese: "忠诚"
      context: "性关系状态"
      priority: "high"
    
    - english: "infidelity"
      chinese: "不忠"
      context: "性关系状态"
      priority: "high"
    
    # 性相关情感
    - english: "passion"
      chinese: "激情"
      context: "情感描述"
      priority: "high"
    
    - english: "intimacy"
      chinese: "亲密"
      context: "情感描述"
      priority: "high"
    
    - english: "romance"
      chinese: "浪漫"
      context: "情感描述"
      priority: "high"
    
    - english: "seduction"
      chinese: "诱惑"
      context: "行为描述"
      priority: "high"
    
    - english: "flirt"
      chinese: "调情"
      context: "行为描述"
      priority: "high"
    
    # 性相关动作
    - english: "kiss"
      chinese: "接吻"
      context: "亲密动作"
      priority: "high"
    
    - english: "hug"
      chinese: "拥抱"
      context: "亲密动作"
      priority: "high"
    
    - english: "caress"
      chinese: "爱抚"
      context: "亲密动作"
      priority: "high"
    
    - english: "fondle"
      chinese: "抚摸"
      context: "亲密动作"
      priority: "high"
    
    - english: "touch"
      chinese: "触摸"
      context: "亲密动作"
      priority: "high"
    
    # 性相关描述词
    - english: "naked"
      chinese: "裸体"
      context: "身体状态"
      priority: "high"
    
    - english: "nude"
      chinese: "裸体"
      context: "身体状态"
      priority: "high"
    
    - english: "bare"
      chinese: "裸露"
      context: "身体状态"
      priority: "high"
    
    - english: "exposed"
      chinese: "暴露"
      context: "身体状态"
      priority: "high"
    
    - english: "clothed"
      chinese: "穿着衣服"
      context: "身体状态"
      priority: "high"
    
    - english: "dressed"
      chinese: "穿着"
      context: "身体状态"
      priority: "high"
    
    # 性相关时间
    - english: "forever"
      chinese: "永远"
      context: "时间描述"
      priority: "high"
    
    - english: "eternity"
      chinese: "永恒"
      context: "时间描述"
      priority: "high"
    
    - english: "moment"
      chinese: "瞬间"
      context: "时间描述"
      priority: "high"
    
    - english: "instant"
      chinese: "瞬间"
      context: "时间描述"
      priority: "high"
    
    # 暴力性行为相关
    - english: "rape"
      chinese: "强奸"
      context: "暴力性行为"
      priority: "high"
      note: "翻译API可能过滤此内容"
    
    - english: "raping"
      chinese: "强奸"
      context: "暴力性行为"
      priority: "high"
    
    - english: "raped"
      chinese: "被强奸"
      context: "暴力性行为"
      priority: "high"
    
    - english: "bestiality"
      chinese: "兽交"
      context: "性行为方式"
      priority: "high"
      note: "翻译API可能过滤此内容"
    
    - english: "beastiality"
      chinese: "兽交"
      context: "性行为方式"
      priority: "high"
    
    # 超自然性内容
    - english: "succubus"
      chinese: "魅魔"
      context: "超自然生物"
      priority: "high"
    
    - english: "succubi"
      chinese: "魅魔"
      context: "超自然生物"
      priority: "high"
    
    - english: "incubus"
      chinese: "梦魔"
      context: "超自然生物"
      priority: "high"
    
    - english: "incubi"
      chinese: "梦魔"
      context: "超自然生物"
      priority: "high"
    
    # 性相关描述
    - english: "dirty dreams"
      chinese: "淫梦"
      context: "性相关描述"
      priority: "high"
    
    - english: "sexual prowess"
      chinese: "性能力"
      context: "性相关描述"
      priority: "high"
    
    - english: "prowess"
      chinese: "能力"
      context: "能力描述"
      priority: "medium"
    
    - english: "seduce"
      chinese: "诱惑"
      context: "性行为动作"
      priority: "high"
    
    - english: "seduction"
      chinese: "诱惑"
      context: "性行为动作"
      priority: "high"
    
    - english: "seducing"
      chinese: "诱惑"
      context: "性行为动作"
      priority: "high"
    
    # 性相关状态
    - english: "desperate"
      chinese: "绝望的"
      context: "心理状态"
      priority: "medium"
    
    - english: "desperation"
      chinese: "绝望"
      context: "心理状态"
      priority: "medium"
    
    # 性相关物品/概念
    - english: "fertilin"
      chinese: "生育素"
      context: "游戏概念"
      priority: "high"
      note: "游戏特有概念"
    
    - english: "low fertilin"
      chinese: "生育素不足"
      context: "游戏状态"
      priority: "high"
    
    - english: "zero fertilin"
      chinese: "生育素为零"
      context: "游戏状态"
      priority: "high"
    
    # 性相关动作
    - english: "fed"
      chinese: "进食"
      context: "动作描述"
      priority: "medium"
    
    - english: "feeding"
      chinese: "进食"
      context: "动作描述"
      priority: "medium"
    
    - english: "feeds"
      chinese: "进食"
      context: "动作描述"
      priority: "medium"
    
    # 性相关描述词
    - english: "dirty"
      chinese: "肮脏的"
      context: "描述词"
      priority: "medium"
    
    - english: "impressed"
      chinese: "印象深刻"
      context: "心理状态"
      priority: "medium"
    
    - english: "impress"
      chinese: "印象深刻"
      context: "心理状态"
      priority: "medium"
    
    - english: "impressing"
      chinese: "印象深刻"
      context: "心理状态"
      priority: "medium"
    
    # 性相关时间描述
    - english: "couple of days"
      chinese: "几天"
      context: "时间描述"
      priority: "low"
    
    - english: "hang around"
      chinese: "逗留"
      context: "行为描述"
      priority: "low"
    
    - english: "decide to join"
      chinese: "决定加入"
      context: "行为描述"
      priority: "low"
    
    - english: "decided to stay"
      chinese: "决定留下"
      context: "行为描述"
      priority: "low"
    
    - english: "enjoys it here"
      chinese: "喜欢这里"
      context: "情感描述"
      priority: "low"
    
    # 补充词汇
    - english: "guest joins"
      chinese: "客人加入"
      context: "游戏事件"
      priority: "low"
    
    - english: "guest"
      chinese: "客人"
      context: "角色类型"
      priority: "low"
    
    - english: "joins"
      chinese: "加入"
      context: "行为动作"
      priority: "low"
    
    - english: "colonist"
      chinese: "殖民者"
      context: "游戏角色"
      priority: "medium"
    
    - english: "colonists"
      chinese: "殖民者们"
      context: "游戏角色"
      priority: "medium"
    
    - english: "colony"
      chinese: "殖民地"
      context: "游戏概念"
      priority: "medium"